name: Test sort forks

on: [push]

jobs:
  test_issue_tracker:
    runs-on: ubuntu-latest
    name: A job to test sort forks
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Sort forks
      id: sort
      uses: ./
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Git commit
      run: |
        # git commit if there's any change
        if test -n "$(git status --porcelain 2>/dev/null)"; then
            git config --global user.email "idegorepl@gmail.com"
            git config --global user.name "ActionCloud Bot"
            git add .
            git commit -m "Update forks data"
            git push
        fi
    - name: Check output
      run: echo '${{ steps.sort.outputs.actioncloud-badge }}'
